### ISSUE TITLE
Unable to clone repository

### ISSUE THREAD

**Issue by LordWeedlle** [symfony-bundle/bootstrap-bundle#1]
When launching command ```composer update symfony-bundle/bootstrap-bundle``` a prompt asks me for a Username and a Password, and I got the following error:

```
fatal: unable to access 'https://user:***@git.anezi.net/symfony/jquerybundle.git/': SSL certificate problem: certificate has expired
```

**Comment by amouhzi** [comment]
Hello,

This repository is no longer supported.

Using a bundle to integrate bootstrap or jQuery is not a good practice, you can follow this totoriel to integrate jQuery and bootstrap:

https://coderwall.com/p/cx1ztw/bootstrap-3-in-symfony-2-with-composer-and-no-extra-bundles

You can also use Bower:

https://symfony.com/doc/current/frontend/bower.html

**Comment by LordWeedlle** [comment]
OK, thanks for response
